language: node_js

cache: yarn

sudo: false

services:
  - xvfb

addons:
  firefox: "49.0"

notifications:
  email: false

node_js:
  - '12'

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

before_script:
  - npm prune
  - export DISPLAY=:99.0
